## NumPy

NumPy is one of the fundamental packages for scientific computing in Python. It
contains functionality for multidimensional arrays, high-level mathematical func
tions such as linear algebra operations and the Fourier transform, and pseudorandom
number generators.<br>
In scikit-learn, the NumPy array is the fundamental data 
structure. scikit-learn takes in data in the form of NumPy arrays. Any data you’re 
using will have to be converted to a NumPy array. The core functionality of NumPy
is the ndarray class, a multidimensional (n-dimensional) array. All elements of
the array must be of the same type.

In [7]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


## SciPy

SciPy is a collection of functions for scientific computing in Python. It provides,
among other functionality, advanced linear algebra routines, mathematical function
optimization, signal processing, special mathematical functions, and statistical
distributions. scikit-learn draws from SciPy’s collection of functions for implementing
its algorithms. The most important part of SciPy for us is scipy.sparse: this provides
sparse matrices, which are another representation that is used for data in scikit
learn. Sparse matrices are used whenever we want to store a 2D array that contains
mostly zeros

In [8]:
from scipy import sparse
import numpy as np

eye = np.eye(4)
print("Numpy array:\n{}".format(eye))

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Pandas

 pandas is a Python library for data wrangling and analysis. It is built around a data
 structure called the DataFrame that is modeled after the R DataFrame. Simply put, a
 pandas DataFrame is a table, similar to an Excel spreadsheet. pandas provides a great
 range of methods to modify and operate on this table; in particular, it allows SQL-like
 queries and joins of tables. In contrast to NumPy, which requires that all entries in an
 array be of the same type, pandas allows each column to have a separate type (for
 example, integers, dates, floating-point numbers, and strings). Another valuable tool
 provided by pandas is its ability to ingest from a great variety of file formats and data
bases, like SQL, Excel files, and comma-separated values (CSV) files.

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Address': ['Bogura', 'Dhaka', 'Chittagong']
}

data_pandas = pd.DataFrame(data)

display(data_pandas)

Name  Age     Address
0    Alice   25      Bogura
1      Bob   30       Dhaka
2  Charlie   35  Chittagong